version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: three_tier_db
    networks:
      - DevOps
    container_name: sqlserver
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: vishwajith19/flaskwithmetrics:practice0.1
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - DevOps
    container_name: flask  # Naming the Flask container

networks:
  DevOps:
    external: true  # Specify that the network is external
